[package]
name = "tetris"
version = "0.1.0"
authors = ["Christian Sigl <christian.sigl@wrkwks.at>"]
edition = "2018"

[dependencies]
#sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2" }
sdl2 = "0.30.0"

[features]
default = ["sdl2/image"]
